### ISSUE TITLE
Installation trouble with webui

### ISSUE THREAD

**Issue by mischaschaub** [jhj0517/stable-diffusion-webui-MusePose#9]
[error.txt](https://github.com/user-attachments/files/15777110/error.txt)

Get this error while starting up with the musepose extension installed. Please advice!

**Comment by jhj0517** [comment]
Hi. This error occurs because SD webui's venv prevents installing `opencv-contrib-python`.

To resolve this, you have to mannually actiavte venv and install these dependencies in the terminal.

1. Open the terminal in the WebUI and activate the venv
```
C:\YourPath\To_SD_WebUI>venv\Scripts\activate
```
Then it will display (venv) in front of the terminal like this.
```
(venv) C:\YourPath\To_SD_WebUI>
```
In this state, run
```
pip uninstall opencv-python-headless
pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip install opencv-python
pip install opencv-contrib-python
 ```
 
 This is in the [ReadMe](https://github.com/jhj0517/stable-diffusion-webui-MusePose/tree/master?tab=readme-ov-file#troubleshooting-installation)

**Comment by mischaschaub** [comment]
Thanks very much for your super quick answer, will try this, with an excuse for my useless question. Was in the train all day long and getting a bit gaga ...
